language: scala
scala:
- 2.12.7
jdk:
- oraclejdk8
script:
- "./gradlew clean build"
deploy:
  provider: releases
  api_key:
    secure: OG4PU4CZm2N5MpLpO0x1LlLgdjEUpUOl1JF0gQRdPvAdTDNKGjSIKz2YP57tfJ4vrXWk8icKi6tcUrpKxGRQX61ZRdPG36E7+3gqxaWvB0ssn8HyT20gNddO8c09x6IVoa4agO64Q6nzWw1MJMVOmWzJ6OFSCvjftXzfo9+bkGjdn5HuPQU58MNnwG4cliaD56TYbKRTSJj9uHDbe4I8iMeirrSv9GAi50YCJ3Uipa9XC903oZEx3veuDM/pfiqM/MZ/zzWqz2q+mk4qOyhAnU5XYitL9D09jyZbzqcLqM3QnnVjwSBtGIbi/ZCnZ/mlIrkU1rwsoPF1mhN+Z14n1RGpZY5rMeLFPyZvgA4um2pW+89p/HZENbSGxLfRr7lnbCaxdZfFQIy2cevunaNL6Nnnpkab2OAz8WzntJrlPUEQ7y7e7dXUFc2P5Yvicw5ip8Z0rwpK+8PL+EZfcI/kouE2NSeNlC5lQ7SajQ/I5emwaOkOTIFT3kn1LMQoXhjNrkLV9t9JffCa7cmXZ5k3Vg+4ea8SmTQC7SX+FmJ0c6gtzGm94agdTXipLql2Kl6bPlLYRA3dY5PlihtMpGVQq6D6QjRqEcTg1jOccF3WtNhfZExTB54ufQghxjFQx19Dx8vnb5GQt6e4LC6k04DYjZ3NmrmQCxDKfBcCB85dSLo=
  file: productions/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: nicolaAtti/pps-17-fb
    branch: develop
